# Generated by Django 5.2.4 on 2025-07-31 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XUIServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(help_text='نام سرور', max_length=100)),
                ('host', models.CharField(help_text='آدرس سرور', max_length=255)),
                ('port', models.IntegerField(default=54321, help_text='پورت X-UI')),
                ('username', models.CharField(help_text='نام کاربری X-UI', max_length=100)),
                ('password', models.CharField(help_text='رمز عبور X-UI', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='آیا سرور فعال است؟')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('xui_inbound_id', models.IntegerField(help_text='شناسه inbound در X-UI')),
                ('xui_user_id', models.IntegerField(help_text='شناسه کاربر در X-UI')),
                ('config_name', models.CharField(help_text='نام کانفیگ', max_length=100)),
                ('config_data', models.TextField(help_text='داده\u200cهای کانفیگ (vmess/vless)')),
                ('is_active', models.BooleanField(default=True, help_text='آیا کانفیگ فعال است؟')),
                ('expires_at', models.DateTimeField(blank=True, help_text='تاریخ انقضا', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xui_configs', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_configs', to='xui_servers.xuiserver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
