# Generated by Django 5.2.4 on 2025-08-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('xui_servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='آیا کانفیگ تستی است؟'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='پلن مرتبط', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.confingplansmodel'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='protocol',
            field=models.CharField(default='vless', help_text='پروتکل کانفیگ', max_length=20),
        ),
    ]
