# Generated by Django 5.2.4 on 2025-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xui_servers', '0002_userconfig_is_trial_userconfig_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='xui_user_id',
            field=models.CharField(help_text='شناسه کاربر در X-UI', max_length=100),
        ),
    ]
