# Generated by Django 5.2.4 on 2025-08-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xui_servers', '0003_alter_userconfig_xui_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuiserver',
            name='web_base_path',
            field=models.CharField(default='/MsxZ4xuIy5xLfQtsSC/', help_text='مسیر وب X-UI', max_length=100),
        ),
    ]
