# Generated by Django 5.2.8 on 2025-11-27 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xui_servers', '0004_xuiserver_web_base_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XUIInbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('xui_inbound_id', models.IntegerField(help_text='شناسه inbound در X-UI')),
                ('port', models.IntegerField(help_text='پورت inbound')),
                ('protocol', models.CharField(default='vless', help_text='پروتکل (vless, vmess, trojan)', max_length=20)),
                ('remark', models.CharField(help_text='نام inbound', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='آیا inbound فعال است؟')),
                ('max_clients', models.IntegerField(default=100, help_text='حداکثر تعداد کلاینت')),
                ('current_clients', models.IntegerField(default=0, help_text='تعداد کلاینت\u200cهای فعلی')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='xui_servers.xuiserver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XUIClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('xui_client_id', models.CharField(help_text='شناسه کلاینت در X-UI', max_length=100)),
                ('email', models.CharField(help_text='ایمیل کلاینت', max_length=100)),
                ('total_gb', models.BigIntegerField(default=0, help_text='حجم کل (GB)')),
                ('used_gb', models.BigIntegerField(default=0, help_text='حجم استفاده شده (GB)')),
                ('expiry_time', models.BigIntegerField(default=0, help_text='زمان انقضا')),
                ('limit_ip', models.IntegerField(default=0, help_text='محدودیت IP')),
                ('is_active', models.BooleanField(default=True, help_text='آیا کلاینت فعال است؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xui_clients', to=settings.AUTH_USER_MODEL)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='xui_servers.xuiinbound')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userconfig',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_configs', to='xui_servers.xuiinbound'),
        ),
    ]
