# Generated by Django 4.2.27 on 2025-12-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xui_servers', '0005_xuiinbound_xuiclient_userconfig_inbound'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'به\u200cروزرسانی'), ('delete', 'حذف'), ('activate', 'فعال\u200cسازی'), ('deactivate', 'غیرفعال\u200cسازی'), ('sync', 'همگام\u200cسازی'), ('provision', 'تامین'), ('deprovision', 'حذف تامین')], help_text='عمل انجام شده', max_length=20)),
                ('model_name', models.CharField(help_text='نام مدل', max_length=100)),
                ('object_id', models.CharField(help_text='شناسه شی', max_length=100)),
                ('description', models.TextField(help_text='توضیحات')),
                ('changes', models.JSONField(blank=True, help_text='تغییرات', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='آدرس IP', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userconfig',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='شناسه خارجی برای idempotency', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='last_provision_error',
            field=models.TextField(blank=True, help_text='آخرین خطای تامین', null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='آخرین همگام\u200cسازی', null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='provision_retry_count',
            field=models.IntegerField(default=0, help_text='تعداد تلاش برای تامین'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('active', 'فعال'), ('expired', 'منقضی شده'), ('suspended', 'معلق'), ('cancelled', 'لغو شده')], default='pending', help_text='وضعیت کانفیگ', max_length=20),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='subscription_url',
            field=models.URLField(blank=True, help_text='لینک اشتراک', null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='sync_required',
            field=models.BooleanField(default=False, help_text='نیاز به همگام\u200cسازی'),
        ),
        migrations.AddField(
            model_name='xuiclient',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='آخرین خطای همگام\u200cسازی', null=True),
        ),
        migrations.AddField(
            model_name='xuiclient',
            name='last_usage_sync',
            field=models.DateTimeField(blank=True, help_text='آخرین همگام\u200cسازی استفاده', null=True),
        ),
        migrations.AddField(
            model_name='xuiclient',
            name='sync_retry_count',
            field=models.IntegerField(default=0, help_text='تعداد تلاش برای همگام\u200cسازی'),
        ),
        migrations.AddField(
            model_name='xuiinbound',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='آخرین همگام\u200cسازی', null=True),
        ),
        migrations.AddField(
            model_name='xuiinbound',
            name='sniffing_settings',
            field=models.JSONField(blank=True, help_text='تنظیمات Sniffing', null=True),
        ),
        migrations.AddField(
            model_name='xuiinbound',
            name='stream_settings',
            field=models.JSONField(blank=True, help_text='تنظیمات Stream', null=True),
        ),
        migrations.AddField(
            model_name='xuiserver',
            name='api_token',
            field=models.CharField(blank=True, help_text='API Token برای S-UI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xuiserver',
            name='health_check_enabled',
            field=models.BooleanField(default=True, help_text='فعال بودن بررسی سلامت'),
        ),
        migrations.AddField(
            model_name='xuiserver',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'سالم'), ('unhealthy', 'ناسالم'), ('unknown', 'نامشخص')], default='unknown', help_text='وضعیت سلامت', max_length=20),
        ),
        migrations.AddField(
            model_name='xuiserver',
            name='last_health_check',
            field=models.DateTimeField(blank=True, help_text='آخرین بررسی سلامت', null=True),
        ),
        migrations.AddField(
            model_name='xuiserver',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='آخرین همگام\u200cسازی', null=True),
        ),
        migrations.AddField(
            model_name='xuiserver',
            name='server_type',
            field=models.CharField(choices=[('xui', 'X-UI'), ('sui', 'S-UI')], default='xui', help_text='نوع سرور', max_length=20),
        ),
        migrations.AddField(
            model_name='xuiserver',
            name='sync_interval_minutes',
            field=models.IntegerField(default=15, help_text='فاصله همگام\u200cسازی (دقیقه)'),
        ),
        migrations.AddField(
            model_name='xuiserver',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='استفاده از HTTPS'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='تاریخ انقضا', null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='xui_inbound_id',
            field=models.IntegerField(db_index=True, help_text='شناسه inbound در X-UI'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='xui_user_id',
            field=models.CharField(db_index=True, help_text='شناسه کاربر در X-UI', max_length=100),
        ),
        migrations.AlterField(
            model_name='xuiclient',
            name='email',
            field=models.CharField(db_index=True, help_text='ایمیل کلاینت', max_length=100),
        ),
        migrations.AlterField(
            model_name='xuiclient',
            name='xui_client_id',
            field=models.CharField(db_index=True, help_text='شناسه کلاینت در X-UI', max_length=100),
        ),
        migrations.AlterField(
            model_name='xuiinbound',
            name='xui_inbound_id',
            field=models.IntegerField(db_index=True, help_text='شناسه inbound در X-UI'),
        ),
        migrations.AlterUniqueTogether(
            name='xuiinbound',
            unique_together={('server', 'xui_inbound_id')},
        ),
        migrations.AddIndex(
            model_name='userconfig',
            index=models.Index(fields=['user', 'is_active'], name='xui_servers_user_id_d3dc63_idx'),
        ),
        migrations.AddIndex(
            model_name='userconfig',
            index=models.Index(fields=['user', 'status'], name='xui_servers_user_id_e3a392_idx'),
        ),
        migrations.AddIndex(
            model_name='userconfig',
            index=models.Index(fields=['expires_at', 'is_active'], name='xui_servers_expires_9e88df_idx'),
        ),
        migrations.AddIndex(
            model_name='userconfig',
            index=models.Index(fields=['sync_required'], name='xui_servers_sync_re_075b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='userconfig',
            index=models.Index(fields=['xui_inbound_id', 'xui_user_id'], name='xui_servers_xui_inb_1fc499_idx'),
        ),
        migrations.AddIndex(
            model_name='userconfig',
            index=models.Index(fields=['external_id'], name='xui_servers_externa_ace38b_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiclient',
            index=models.Index(fields=['inbound', 'is_active'], name='xui_servers_inbound_1c52a8_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiclient',
            index=models.Index(fields=['user', 'is_active'], name='xui_servers_user_id_c5955d_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiclient',
            index=models.Index(fields=['email'], name='xui_servers_email_129b48_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiclient',
            index=models.Index(fields=['is_active', 'expiry_time'], name='xui_servers_is_acti_8cfba5_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiinbound',
            index=models.Index(fields=['server', 'is_active'], name='xui_servers_server__3c6593_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiinbound',
            index=models.Index(fields=['protocol', 'is_active'], name='xui_servers_protoco_72154e_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiinbound',
            index=models.Index(fields=['xui_inbound_id'], name='xui_servers_xui_inb_583bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiserver',
            index=models.Index(fields=['is_active', 'is_deleted'], name='xui_servers_is_acti_be89f2_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiserver',
            index=models.Index(fields=['server_type'], name='xui_servers_server__9f1d20_idx'),
        ),
        migrations.AddIndex(
            model_name='xuiserver',
            index=models.Index(fields=['health_status'], name='xui_servers_health__f45c66_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='کاربر انجام\u200cدهنده', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='xui_servers_user_id_a0e61f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='xui_servers_model_n_5bcdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='xui_servers_action_2a0007_idx'),
        ),
    ]
