# Generated by Django 5.2.4 on 2025-07-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='phone',
            field=models.CharField(blank=True, help_text='شماره تلفن (اختیاری)', max_length=20, null=True),
        ),
    ]
