# Generated by Django 5.2.4 on 2025-07-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_phone_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text='آیا کاربر از پلن تستی استفاده کرده است؟'),
        ),
    ]
