"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from celery.schedules import crontab

# Load environment variables from root .env file
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / ".env"
CONFIG_ENV_FILE = BASE_DIR / "config.env"

# Try to load from root .env first, fallback to config.env for backward compatibility
if ENV_FILE.exists():
    load_dotenv(ENV_FILE)
elif CONFIG_ENV_FILE.exists():
    load_dotenv(CONFIG_ENV_FILE)
else:
    # Try to load from current directory
    load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR is already set above for env loading


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'your-very-secure-secret-key-with-more-than-50-characters-and-special-chars-!@#$%^&*()_+=-[]{}|;:,.<>?')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #     rest framework
    'rest_framework',
    
    # Custom apps
    'accounts',
    'core',
    'order',
    'plan',
    'conf',
    'chat_messages',  # renamed from messages to avoid conflict
    'xui_servers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration from environment
# Support both DB_* and DATABASE_* naming conventions
DB_ENGINE = os.environ.get('DB_ENGINE') or os.environ.get('DATABASE_ENGINE', 'django.db.backends.sqlite3')
DB_NAME = os.environ.get('DB_NAME') or os.environ.get('DATABASE_NAME', str(BASE_DIR / 'db.sqlite3'))
DB_USER = os.environ.get('DB_USER') or os.environ.get('DATABASE_USER', '')
DB_PASSWORD = os.environ.get('DB_PASSWORD') or os.environ.get('DATABASE_PASSWORD', '')
DB_HOST = os.environ.get('DB_HOST') or os.environ.get('DATABASE_HOST', '')
DB_PORT = os.environ.get('DB_PORT') or os.environ.get('DATABASE_PORT', '')

if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': DB_NAME,
        }
    }
elif DB_ENGINE in ['django.db.backends.postgresql', 'django.db.backends.postgresql_psycopg2']:
    # Validate required PostgreSQL settings
    if not DB_NAME or not DB_USER or not DB_PASSWORD:
        raise ValueError(
            "PostgreSQL requires DB_NAME, DB_USER, and DB_PASSWORD to be set in .env file. "
            "Current values: DB_NAME={}, DB_USER={}, DB_PASSWORD={}".format(
                'SET' if DB_NAME else 'NOT SET',
                'SET' if DB_USER else 'NOT SET',
                'SET' if DB_PASSWORD else 'NOT SET'
            )
        )
    
    # Determine host - use 'postgres' for Docker, 'localhost' for local
    # Check if we're in Docker by looking for DB_HOST or environment
    db_host = DB_HOST or 'localhost'
    if not DB_HOST and os.environ.get('DOCKER_CONTAINER'):
        db_host = 'postgres'
    elif DB_HOST == 'postgres':
        # Explicitly set for Docker
        db_host = 'postgres'
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': db_host,
            'PORT': DB_PORT or '5432',
            'OPTIONS': {
                'connect_timeout': 10,
            },
            'CONN_MAX_AGE': 600,
        }
    }
else:
    # Default to SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.UsersModel'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# تنظیمات ربات ادمین
ADMIN_BOT_TOKEN = os.environ.get('ADMIN_BOT_TOKEN', '8496586253:AAEOjtvX8uYYjhUEUKVWxyQ8xDSqvF8DkQs')
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', 'admin123')
ADMIN_USER_IDS = [int(x.strip()) for x in os.environ.get('ADMIN_USER_IDS', '123456789').split(',')]

# تنظیمات ربات کاربران
USER_BOT_TOKEN = os.environ.get('USER_BOT_TOKEN', '8496586253:AAEOjtvX8uYYjhUEUKVWxyQ8xDSqvF8DkQs')

# تنظیمات سرور X-UI
XUI_DEFAULT_HOST = os.environ.get('XUI_DEFAULT_HOST', 'time.amirprogrammer.ir')
XUI_DEFAULT_PORT = int(os.environ.get('XUI_DEFAULT_PORT', '50987'))
XUI_DEFAULT_USERNAME = os.environ.get('XUI_DEFAULT_USERNAME', 'bUZC0Iovb9')
XUI_DEFAULT_PASSWORD = os.environ.get('XUI_DEFAULT_PASSWORD', '4jb7doDQZg')
XUI_WEB_BASE_PATH = os.environ.get('XUI_WEB_BASE_PATH', '/YvIhWQ3Pt6cHGXegE4/')

# تنظیمات HTTPS برای X-UI
XUI_USE_SSL = os.environ.get('XUI_USE_SSL', 'True').lower() == 'true'
XUI_VERIFY_SSL = os.environ.get('XUI_VERIFY_SSL', 'False').lower() == 'true'
XUI_TIMEOUT = int(os.environ.get('XUI_TIMEOUT', '30'))

# تنظیمات ایمیل
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'your_email@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'your_email_password')

# تنظیمات پروتکل‌های VPN
DEFAULT_PROTOCOL = os.environ.get('DEFAULT_PROTOCOL', 'vless')
MIN_PORT = int(os.environ.get('MIN_PORT', '10000'))
MAX_PORT = int(os.environ.get('MAX_PORT', '65000'))

# تنظیمات زمان انقضا
TRIAL_HOURS = int(os.environ.get('TRIAL_HOURS', '24'))
PAID_DAYS = int(os.environ.get('PAID_DAYS', '30'))
EXPIRY_WARNING_HOURS = int(os.environ.get('EXPIRY_WARNING_HOURS', '6'))
EXPIRY_WARNING_MESSAGE = os.environ.get(
    'EXPIRY_WARNING_MESSAGE',
    'کانفیگ شما تا {hours} ساعت دیگر منقضی می‌شود ⏰',
)

# تنظیمات امنیت
TLS_ENABLED = os.environ.get('TLS_ENABLED', 'True').lower() == 'true'
REALITY_ENABLED = os.environ.get('REALITY_ENABLED', 'True').lower() == 'true'

# تنظیمات نام‌گذاری
TRIAL_INBOUND_PREFIX = os.environ.get('TRIAL_INBOUND_PREFIX', 'TrialBot')
PAID_INBOUND_PREFIX = os.environ.get('PAID_INBOUND_PREFIX', 'PaidBot')
USER_INBOUND_PREFIX = os.environ.get('USER_INBOUND_PREFIX', 'UserBot')

# تنظیمات اتصال
CONNECTION_TIMEOUT = int(os.environ.get('CONNECTION_TIMEOUT', '15'))
RETRY_ATTEMPTS = int(os.environ.get('RETRY_ATTEMPTS', '5'))

# تنظیمات پیشرفته
LIMIT_IP_PER_USER = int(os.environ.get('LIMIT_IP_PER_USER', '3'))
MB_TO_GB_CONVERSION = int(os.environ.get('MB_TO_GB_CONVERSION', '1024'))

# تنظیمات پلن‌ها
DEFAULT_TRIAL_PLAN_NAME = os.environ.get('DEFAULT_TRIAL_PLAN_NAME', 'پلن تستی')
DEFAULT_TRIAL_PLAN_DURATION = int(os.environ.get('DEFAULT_TRIAL_PLAN_DURATION', '24'))
DEFAULT_TRIAL_PLAN_TRAFFIC = int(os.environ.get('DEFAULT_TRIAL_PLAN_TRAFFIC', '0'))
DEFAULT_TRIAL_PLAN_PRICE = int(os.environ.get('DEFAULT_TRIAL_PLAN_PRICE', '0'))

# تنظیمات ارز
CURRENCY = os.environ.get('CURRENCY', 'IRR')
CURRENCY_SYMBOL = os.environ.get('CURRENCY_SYMBOL', 'تومان')

# تنظیمات اعلان‌ها
TELEGRAM_NOTIFICATIONS_ENABLED = os.environ.get('TELEGRAM_NOTIFICATIONS_ENABLED', 'True').lower() == 'true'
SYSTEM_MESSAGES_ENABLED = os.environ.get('SYSTEM_MESSAGES_ENABLED', 'True').lower() == 'true'

# تنظیمات پیام‌ها
MESSAGE_LANGUAGE = os.environ.get('MESSAGE_LANGUAGE', 'fa')
MESSAGE_RTL = os.environ.get('MESSAGE_RTL', 'True').lower() == 'true'

# تنظیمات Reality
REALITY_DEST = os.environ.get('REALITY_DEST', 'www.aparat.com:443')
REALITY_SERVER_NAMES = os.environ.get('REALITY_SERVER_NAMES', 'www.aparat.com')
REALITY_PRIVATE_KEY = os.environ.get('REALITY_PRIVATE_KEY', 'YFgo8YQUJmqhu2yXL8rd8D9gDgJ1H1XgfbYqMB6LmoM')

# تنظیمات WebSocket
WS_PATH = os.environ.get('WS_PATH', '/')
WS_HOST = os.environ.get('WS_HOST', '')

# تنظیمات IP و سرور
SERVER_IP = os.environ.get('SERVER_IP', '156.244.31.37')
SERVER_DOMAIN = os.environ.get('SERVER_DOMAIN', 'time.amirprogrammer.ir')
SERVER_PORT = int(os.environ.get('SERVER_PORT', '8000'))
SERVER_PROTOCOL = os.environ.get('SERVER_PROTOCOL', 'http')

# تنظیمات امنیتی
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', f'http://{SERVER_DOMAIN},https://{SERVER_DOMAIN},http://{SERVER_IP},https://{SERVER_IP}').split(',')

# تنظیمات امنیتی اضافی برای production
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true'

# تنظیمات Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'check-expiring-configs-every-15-mins': {
        'task': 'xui_servers.tasks.send_expiry_warnings',
        'schedule': crontab(minute='*/15'),
    },
    'cleanup-expired-and-overused-every-10-mins': {
        'task': 'xui_servers.tasks.cleanup_expired_and_overused',
        'schedule': crontab(minute='*/10'),
    },
}

# تنظیمات پنل S-UI (API v2)
SUI_HOST = os.environ.get('SUI_HOST', 'localhost')
SUI_PORT = int(os.environ.get('SUI_PORT', '2095'))
SUI_USE_SSL = os.environ.get('SUI_USE_SSL', 'False').lower() == 'true'
SUI_BASE_PATH = os.environ.get('SUI_BASE_PATH', '/app')
SUI_API_TOKEN = os.environ.get('SUI_API_TOKEN', '')
