# Generated by Django 5.2.8 on 2025-11-27 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfingPlansModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('in_volume', models.PositiveIntegerField()),
                ('traffic_mb', models.PositiveIntegerField(default=0, help_text='حجم داده به مگابایت')),
                ('is_active', models.BooleanField(default=True, help_text='آیا پلن فعال است؟')),
                ('description', models.TextField(blank=True, help_text='توضیحات پلن', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
