# Generated by Django 4.2.27 on 2025-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confingplansmodel',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='مدت زمان اعتبار به روز'),
        ),
    ]
