# Generated by Django 4.2.27 on 2025-12-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_make_plan_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderusermodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='orderusermodel',
            new_name='order_order_user_id_b1cabf_idx',
            old_name='order_order_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='orderusermodel',
            new_name='order_order_status_5f12db_idx',
            old_name='order_order_status_i_idx',
        ),
        migrations.RenameIndex(
            model_name='orderusermodel',
            new_name='order_order_order_n_89633d_idx',
            old_name='order_order_order_n_idx',
        ),
        migrations.RenameIndex(
            model_name='orderusermodel',
            new_name='order_order_created_c4438f_idx',
            old_name='order_order_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmodel',
            new_name='order_payme_user_id_2cddb3_idx',
            old_name='order_payme_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmodel',
            new_name='order_payme_order_i_4d0aa4_idx',
            old_name='order_payme_order_id_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmodel',
            new_name='order_payme_code_pa_0459bc_idx',
            old_name='order_payme_code_pa_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmodel',
            new_name='order_payme_status_68030e_idx',
            old_name='order_payme_status__idx',
        ),
        migrations.AlterField(
            model_name='orderusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='code_pay',
            field=models.IntegerField(db_index=True, help_text='کد پرداخت'),
        ),
    ]
